apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: default
type: Opaque
data:
  username: YWRtaW4=  # Base64-encoded 'admin'
  password: Y2hhbmdlbWU=  # Base64-encoded 'changeme'
